### ISSUE TITLE
Regression: jest-dom removed from dependencies

### ISSUE THREAD

**Issue by nickmccurdy** [kentcdodds/react-testing-library#146]
- `react-testing-library` version: 4.1.3

### Relevant code or config:

```js
import 'jest-dom/extend-expect'
```

### Problem description:

4.1.3 updates dom-testing-library to 3, which removes its dependency on jest-dom and a re-export. This is a breaking change in react-testing-library, which still documents a `jest-dom` import, causing my tests to fail after updating the package. 

### Suggested solution:

Revert 4.1.3 or deprecate it and release a major release of this library to signify a breaking change and document that jest-dom should be installed manually.

### Workaround:

Install `jest-dom`.

**Comment by kentcdodds** [comment]
Sorry this broke for you @nickmccurdy. I believe that explicit support for the implicit `jest-dom` dependency was removed in react-testing-library 3.0.0 and that's when you were supposed to add `jest-dom` to your dependencies yourself. The fact that dom-testing-library continued to include `jest-dom` was a mistake. I didn't consider this a breaking change in react-testing-library because we'd already changed the documentation to indicate you should install `jest-dom` manually.

I understand where you're coming from, but at this point I don't think many more people will bump into this problem, and considering the major release for this breaking change was technically already released I don't see any value in doing another major release.

Sorry for the confusion.
