### ISSUE TITLE
Testing parent and child components separately

### ISSUE THREAD

**Issue by artooras** [kentcdodds/react-testing-library#167]
This is a general question about using the library correctly, so I hope it's OK to raise it here.

Say, I have the following setup.

**Parent.js**

```
class Parent extends React.Component {

  state = {
    value: '1'
  }

  handleClick = () => {
    const {value} = this.state
    value++
    this.setState(value)
  }

  render() {
    return (
      <Child 
        value={this.state.value}
        onClick={this.handleClick} />
    )
  }
}
```

**Child.js**

```
class Child extends React.Component {
  render() {
    return (
      <button onClick={this.props.onClick}>
        {this.props.value}
      </button>
    )
  }
}
```

Now, I can test the `Child` component to see that the `click` is handled like so:

```
const handleClickMock = jest.fn()
const {container} = render(
  <Child value='1' onClick={handleClickMock} />
)
fireEvent.click(container.firstChild)
expect(handleClickMock).toHaveBeenCalledTimes(1)
```

However, how do I test the functionality of the `Parent` component since the `handleClick` functionality is not exposed in its API and therefore not directly accessible to the user? In theory, following the guiding principles, I could find the `Child` component in the rendered tree of the `Parent` with `getByValue` and fire a click event on that, but wouldn't it be a duplication of effort? If I have such a test implemented, I don't really need a test for the `Child` separately. But, if I follow this approach, I will end up with huge test files for only the top-most components.

So, what is the recommended approach to testing the `Child` callback in the `Parent` component?

**Comment by kentcdodds** [comment]
Hi there @artooras! I responded to your question in my daily livestream today: https://www.youtube.com/watch?v=0qmPdcV-rN8&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

I hope that's helpful!

**Comment by artooras** [comment]
Hi @kentcdodds. "Helpful" is an understatement - it's the first time I could enjoy an answer to my question with popcorn in my hand!

Key takeaways for me:
- E2E test (on Parent) is the preferred approach, as this is how the user experiences the functionality.
- If Child contains local logic which is not exposed to the Parent via props - like internal state management - then it makes sense to test the Child separately to cover that extra logic.

Thanks!

**Comment by kentcdodds** [comment]
Yep! Though I wouldn't call a test on that parent E2E, but that's just semantics 😅

**Comment by wdoug** [comment]
It seems like this would be helpful to link to from the FAQ in the docs as it seems like a frequently asked question

**Comment by kentcdodds** [comment]
That sounds good to me @wdoug. Would you like to make that change?

**Comment by matt-sanders** [comment]
@kentcdodds how deep do you go with this? I was just having this same conversation on another forum, the example use case was to consider you have a component that is used in multiple different other parent components. Let’s say it’s a feedback form that is displayed on a bunch of different screens. We expect it to:
- take some user input
- validate some data
- make a request to an endpoint on submission
- alert on success
- alert on fail

Now when I’m testing the parent components, I don’t really care how this is implemented, which takes stubbing / shallow rendering out of the picture. But do you write the same test for each of the parent components? Or do you maybe abstract the assertions to a re-usable function so that you can run the same tests in various locations. E.g.:
``` js
// tests/common.js
const feedbackFormAssertions = () => {
   it('takes user input', () => {...})
   it('validates data', () => {...})
   it('makes a request', () => {...})
   it...
}
// src/some/component.spec.js
describe('SomeComponent', () => {
   feedbackFormAssertions()
})
```
At the end of the day what the user really cares about is that the screen they're viewing does xyz and that the feedback form works, right?
Using the above method it means that:
- I can re-factor my component without my tests failing and requiring re-writes
- If the API of my child component changes the tests will fail, as opposed to a stubbed version which is what we want to know
- It removes the itch to test implementation details and focus on user applicable events and actions

The alternative is that if this form component is going to be used in a lot of different places we test that component thoroughly in and of itself and then test only the "happy path" in the parent component ( e.g. user can fill out a form and submit ). The only thing with that, is that we could then potentially re-factor our parent component with missing functionality and our tests would still pass. Error cases may not be tested etc, things that are still applicable to the parent in context, but not necessarily handled by the implementation.

Thoughts? I might be getting far to deep down this rabbit hole 🐰

**Comment by matt-sanders** [comment]
@kentcdodds thanks for that reference, that does clarify some things. I guess what I'm really trying to get at is how do we duplicate tests well without just copy pasting the same test. In that article you gave the example of integration testing a login form. That works great if the component is used once, but let's say ( just for argument sake ) that the login form component was used in a few different places. Maybe on the login page, then also on a landing page, and once more on a different landing page. Disregarding that this would be a potentially terrible user experience, would you just re-write the same test for those three scenarios? Or abstract the full test into something a re-usable test? I'll modify your test on that article as an example:
```js
// test/common.js
export const testLoginForm = (LoginForm) => {
   test('login as an existing user', async () => {
     const {
       getByTestId,
       container,
       getByText,
       getByLabelText,
       finishLoading,
     } = render(LoginForm)

     // fill out form
     const fakeUser = generate.loginForm()
     const usernameNode = getByLabelText(/username/i)
     const passwordNode = getByLabelText(/password/i)
     usernameNode.value = fakeUser.username
     passwordNode.value = fakeUser.password

      // ... the rest of your test here...
   })
})
```
```js
// views/Login.spec.js
import testLoginForm from '../test/common'

describe('Login', () => {
   testLoginForm(LoginView)
})
```
```js
// views/LandingPage.spec.js
import testLoginForm from '../test/common'

describe('LandingPage', () => {
   testLoginForm(LandingPage)
})
```
```js
// views/LandingPage2.spec.js
import testLoginForm from '../test/common'

describe('LandingPage2', () => {
   testLoginForm(LandingPage2)
})
```
But maybe this is getting beyond the scope of this issue

**Comment by matt-sanders** [comment]
💡 this makes a lot of sense. Thanks Kent, really appreciate the time you put in to all this!

**Comment by zach446** [comment]
@kentcdodds Thanks for the link to your daily podcast.  My team just integrated into using hooks and using the testing library.  Your work is really great and the videos are super helpful!  Thanks again!

**Comment by kentcdodds** [comment]
I'm glad it's been helpful to you @zach446! :)

**Comment by mishkinf** [comment]
@kentcdodds If we were to isolate writing tests to just the Parent component or just the child component, we are sort of forced to duplicate tests in order to have real test coverage. In the video for example you suggested writing the test in the parent component and ignoring the child. However, the example is a bit too trivial for real world scenarios. Most people abstract away components so they can be reused. This would mean that every parent would have to contain many overlapping tests for the common behaviors. We can't rely on just testing the child component and having full test coverage either since that doesn't test that the parents actually have the proper behaviors.

It seems to me that react-testing-library might be improved if there was a pattern or example for abstracting the testing of certain expected behaviors so that parents could reuse expectations of behaviors without having to write the same tests over again. Of course I plead ignorance as I am just becoming familiar with your library so maybe I am wrong or this is a solved issue. 

Okay so assuming my premise is correct:

```
const Child = ({person, showName, showAge}) => {
  return <div>
    { showName && <h1>{person.name}</h1> }
    { showAge && <div>{person.age}</div> }
  </div>;
}
const Parent1 = ({person}) => {
  return (<div>
    <Child showName={person.age >= 18} person={person} showAge={false} />
  </div>);
}
const Parent2 = ({person}) => {
  return (<div>
    <Child showName={person.age >= 18} person={person} showAge={true} />
  </div>);
}

// In this example we see that just testing Child 
// would not encompass the logic and behavior desired for Parent1 or Parent2
// If we test just Parent1 or Parent2 then we aren't capturing all of the behavior in tests
// If we test all the behavior of both Parent1 and Parent2 in their respective test files, we are double testing
// Or we are forced to understand which behavior Parent1 has tested and Parent2 has tested and we have to go out
// of our way to ensure we aren't duplicated tests:

describe("Parent1", () => {
  it("should render the person's name when he or she is age 18 or over", () => {
    const person = {
      name: "Mishkin",
      age: 33
    }
    const { queryByText } = render(<Parent1 person={person} />)
  
    expect(queryByText("Mishkin")).toBeInTheDocument();
  });

  it("should not render the person's name when he or she is under the age of 18", () => {
    const person = {
      name: "Timmy",
      age: 3
    }
    const { queryByText } = render(<Parent1 person={person} />)
  
    expect(queryByText("Timmy")).not.toBeInTheDocument();
  });

  it("should not render the person's age", () => {
    // test
  });
});

describe("Parent2", () => {
  it("should render the person's name when he or she is age 18 or over", () => {
    const person = {
      name: "Mishkin",
      age: 33
    }
    const { queryByText } = render(<Parent2 person={person} />)
  
    expect(queryByText("Mishkin")).toBeInTheDocument();
  });

  it("should not render the person's name when he or she is under the age of 18", () => {
    const person = {
      name: "Timmy",
      age: 3
    }
    const { queryByText } = render(<Parent2 person={person} />)
  
    expect(queryByText("Timmy")).not.toBeInTheDocument();
  });

  it("should render the person's age", () => {
    // test
  });
});

// **** POSSIBLE IDEAS / SOLUTIONS **** to not have the trade off between double testing and sifting through components 
// to see if all your logic and behaviors are tested?

// Possible shared behaviors? 

const shouldDisplayAdultNames = (MyComponent) => {
  it("should render the person's name when he or she is age 18 or over", () => {
    const person = {
      name: "Mishkin",
      age: 33
    }
    const { queryByText } = render(<MyComponent person={person} />)
  
    expect(queryByText("Mishkin")).toBeInTheDocument();
  });

  it("should not render the person's name when he or she is under the age of 18", () => {
    const person = {
      name: "Timmy",
      age: 3
    }
    const { queryByText } = render(<MyComponent person={person} />)
  
    expect(queryByText("Timmy")).not.toBeInTheDocument();
  });
}

describe("Parent1", () => {
  shouldDisplayAdultNames(Parent1);

  it("should not render the person's age ever", () => {
    // test
  });
});

describe("Parent2", () => {
  shouldDisplayAdultNames(Parent2);

  it("should render the person's age always", () => {
    // test
  });
});
```

**Comment by eps1lon** [comment]
> This would mean that every parent would have to contain many overlapping tests for the common behaviors.

This is not a bad thing. I see this very often that people stress way to much over the minimal amount of tests to cover just the right amount of lines. Tests are not your production code. They document specified behavior not what your component does internally. If you don't cover certain lines either throw them out, write a new test for them that arranges the behavior the line in question is supposed to cover, or add a big comment block explaining why this line is there.

If your parent and child are tightly coupled only write (integration) tests that use both and document that they are only supposed to use each other.

**Comment by mishkinf** [comment]
@eps1lon The reason I wanted to respond with that gist example is because the example used in the video Kent made is not complex enough to depict a very common scenario when you have a reusable component. If we do test reusable components I think a paradigm of writing shared behavior tests is probably more ideal than writing the same tests possibly tens of times in different places. Make sure to check out the gist I dropped above to see the example of what _a_ possible way to not have to deal with that might be. I just made it quickly for the sake of sharing with the community. It probably can be done in a more elegant way but there are only so many hours in a day. :)

**Comment by alexkrolick** [comment]
In the example given, I would probably start by testing the main desired behavior for Person1 and Person2 while pretending the Child helper doesn't exist (eg as if it was it is inlined in both implementations). If the requirements diverge and you can't actually use the same helper component, the tests will tell you if the refactor worked. Then, take a look at the helper component and see if it has edge cases that would come up if someone wanted to use it in more places, and add tests for that. If the helper becomes really complicated, has really good internal tests for its public methods (props and ui driven), and/or is used in so many places that its API is more or less set in stone (like a design system component), then you might consider using jest.spyOn sometimes in parent tests to assert it is called with certain props rather than verifying the exact behavior from that point down. You can also mock it out with a simpler component if, for example, it is a 3rd party component that has difficulty running in the test env or has side-effects. However you may want to add higher-level tests like Cypress, Selenium, or Puppeteer to verify the integration with such libraries.

**Comment by mishkinf** [comment]
@alexkrolick The only comment I would have is that if you rely on something like jest.spyOn and assert props are being passed properly, you've taken the notion of behavior driven testing and thrown it out the door. It seems like for components that are being reused, we can maintain the behavior driven ethic, and even test drive our components if we rely on a pattern similar to what I depicted. High level integration tests are a given for sure. I think there is always a balance of how granular your unit tests should be. Many times Cypress tests are good at capturing high level happy paths and error paths but are not as ideal for all the possible changes of every possible behavior described on a page so I think it makes sense to do some of that using react-testing-library.

**Comment by jsoneaday** [comment]
What about child components with slow running code. Like network or filesystem calls. Testing the parent would make my parent call slow and potentially prone to failure (network connection lost, file not found, etc). These may not directly relate to my test of the parent ...

**Comment by nickmccurdy** [comment]
Testing with real network/filesystem/etc usage leads to much more reliable tests. While they may run slower, you'll likely save much more time by not having brittle or unrealistic tests.

**Comment by kentcdodds** [comment]
As for network requests, I typically reserve full network requests for E2E tests (because making actual network requests requires a lot more work and increases the failure surface area). However, the approach you take to mocking those requests out can really simplify your tests: https://kentcdodds.com/blog/stop-mocking-fetch
