### ISSUE TITLE
POST under _mocks_

### ISSUE THREAD

**Issue by alejandronanez** [kentcdodds/react-testing-library#2]
Problem description:
Hey Kent,
I see the lib only has a `get` method under `_mocks_`, I guess it will be nice to have a `POST` method too. If that sounds good to you I can take a look at it.

Thanks!

**Comment by kentcdodds** [comment]
Thanks @alejandronanez! We could definitely make the mock more fully-featured, but I think we should leave it for now because we don't need any other functionality.

That said, if you'd like to add a comment to that file explaining this fact so nobody else has the same concern that would be helpful! Thanks!

**Comment by alejandronanez** [comment]
Sure! I’ll do it!

Thanks!!!!

**Comment by kentcdodds** [comment]
Thanks for your help!

**Comment by alejandronanez** [comment]
My pleassure!
