### ISSUE TITLE
Add wrapper option to render/testHook

### ISSUE THREAD

**Issue by alexkrolick** [kentcdodds/react-testing-library#293]
See https://github.com/kentcdodds/react-testing-library/issues/283#issuecomment-462509256

- [x] testHook
- [ ] render

**Comment by FredyC** [comment]
I am thinking if we really need it as a `wrapper` option. I mean @kentcdodds is against making that utility more complicated and using options object would kinda imply to be open for further customization later. Besides, it would make things slightly more readable imo.

```jsx
// define
const testHookWithNameContext = (callback, wrapperProps) => {
  let result
  testHook(
    () => {
      result = callback()
    },
    props => <NameContext.Provider {...wrapperProps} {...props} />,
  )
  return result
}

// use
const [a, b] = testHookWithNameContext(myCustomHook, {value: "ABC"})
```

**Comment by alexkrolick** [comment]
I _think_ I still prefer the option object and here's why:


Positional arguments can be confusing for uncommon options. Someone new to a codebase can figure out what {wrapper} means but would have to look in the docs for the meaning of the second argument and might think it's somehow required.

For `render`, `wrapper` will fit in with the other options that already exist. You can say "the second argument is passed as the options to the render function" and you only need to document the usage one time (plus examples as needed).

**Comment by FredyC** [comment]
Ok, I agree with your reasoning. I will take a stab at this probably today as I need it in my codebase anyway.

**Comment by FredyC** [comment]
One thing might be rather confusing in case of more complex wrapper. What to do with passed `props` user might wonder.

```jsx
const testHookWithContexts = (callback, { nameValue, otherValue }) => {
  let result
  testHook(
    () => {
      result = callback()
    },
    props => (
      <NameContext.Provider value={nameValue}>
        <OtherContext.Provider value={otherValue} {...props} />
      </NameContext.Provider>
    )
  )
  return result
}
```

In this case, the `props` are really just a `{ children }` because `testHook` is not passing any other props to `render` call. We would need to clearly document that these props need to be spread on the lowest element in the wrapper tree 😕

I was thinking for a moment to utilize `React.cloneElement` here, but that won't work either for these complex scenarios.

Alternative approach could be passing array of nodes and let the `testHook` to build a tree from it and apply `children` to last of them.

**Comment by FredyC** [comment]
@alexkrolick Feel free to close, forgot to use a magic word in the PR :)

**Comment by alexkrolick** [comment]
@FredyC good point that figuring out where to put ...props is confusing. Better to destructure ({children}) in the docs I think.
