### ISSUE TITLE
Support for React 15 Context

### ISSUE THREAD

**Issue by oscarkwan** [kentcdodds/react-testing-library#306]
Will there be support for the legacy context api for react-testing-library?

**Comment by kentcdodds** [comment]
Hi @oscarkwan,

There is already. What about it is not working?

**Comment by oscarkwan** [comment]
Hi @kentcdodds,

Thanks for your reply, I'm pretty new to all this and I couldn't find any documentation regarding support for react 15 legacy context api. All the documentation seemed to be about react 16 context.

Do you mind pointing me towards the right direction?

Cheers!

**Comment by kentcdodds** [comment]
Well, it kinda depends on how your legacy context is setup, but the concept is the same whether you're using legacy context or current context. This is because react-testing-library doesn't allow you to test implementation details.

Anyway, here's an example: https://codesandbox.io/s/10w35qy5vq

Good luck.

**Comment by oscarkwan** [comment]
Thanks so much, for the example. This is a good start for me. Still learning react and actually recently watching your javascript testing course.

Cheers!
