### ISSUE TITLE
Weird behaviour with checkbox

### ISSUE THREAD

**Issue by baruchvlz** [kentcdodds/react-testing-library#309]
- `react-testing-library` version: 6
- `react` version: 16.8.3
- `node` version: 10.15.0
- `npm` (or `yarn`) version: 6.4.1

### What you did:

Test `fireEvent.click` on a `input[type=checkbox]`

### What happened:
When testing with `getByTestId` or `baseElement.querySelector` the test fails, but using `container.querySelector` it passes.

### Reproduction:
https://codesandbox.io/s/wnk0x07myl

### Suggested solution:
Pass `container` instead of `baseElement` here: https://github.com/kentcdodds/react-testing-library/blob/master/src/index.js#L70

**Comment by kentcdodds** [comment]
Sadly this is a codesandbox issue. Because the tests and application share the same dom in codesandbox you're seeing this.

Here's a fixed version: https://codesandbox.io/s/vnx50q5o80 (note that we're not rendering the checkbox in the app and the tests work).

Would you be willing to [open an issue on codesandbox](https://github.com/CompuIves/codesandbox-client/issues/new)?

**Comment by weyert** [comment]
I think in general KRTL and Codesandbox don't always work well together in
the browser

**Comment by baruchvlz** [comment]
@kentcdodds Thanks for the response, I didn't think that this might've been a codesandbox issue and should've tried it locally. Cheers.
