### ISSUE TITLE
jest-dom documentation broken link

### ISSUE THREAD

**Issue by besartberisha** [kentcdodds/react-testing-library#324]
Hey there, as I was going through the documentation I noticed a broken link and thought of reporting it here. 

- `react-testing-library` version: N/A
- `react` version: N/A
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

### Relevant code or config:

N/A

### What you did:

1. Go to [jest-dom](https://testing-library.com/docs/ecosystem-jest-dom) page of the documentation.
2. Click in "Check out **jest-dom's documentation** for a full list of available matchers"
3. See that the link is broken. 
### What happened:

The link seems to be broken. 
<img width="1107" alt="Screen Shot 2019-03-18 at 7 41 52 PM" src="https://user-images.githubusercontent.com/7255779/54554936-f2078c80-49b5-11e9-85b4-df31f6116fe8.png">

### Reproduction:

See "What you did" section

### Problem description:

It should send you to the correct documentation page.

### Suggested solution:

Update and fix the broken link.

**Comment by gnapse** [comment]
I did notice this a while ago and made a mental note to report it. Guess my mental notes are not working as expected. Thanks for bringing this up!

BTW, I think that for issues on the documentation site, [this is the repo](https://github.com/alexkrolick/testing-library-docs) where you should've reported this. However, leave it as is right now, because I bet @kentcdodds can move this issue to that repo, since github allows that now.
