### ISSUE TITLE
Setting pointerEvents to 'none' does not disable clicking

### ISSUE THREAD

**Issue by LukenAgile42** [kentcdodds/react-testing-library#356]
```
import 'react-testing-library/cleanup-after-each'
import React from "react";
import {
	render,
	fireEvent
} from "react-testing-library";
import "jest-dom/extend-expect";


test("Setting pointEvents to none disables clicking", () => {
	const onFooClick = jest.fn()
	const {getByTestId} = render(
            <button data-testid="foo"  onClick={onFooClick}
		      style={{pointerEvents: 'none'}}
	/>)
	getByTestId("foo").style.pointerEvents = 'none'
	fireEvent.click(getByTestId("foo"))
	expect(getByTestId("foo").style.pointerEvents).toEqual('none') //passes
	expect(onFooClick).not.toHaveBeenCalled() //fails
})
```

`    
    "jest-dom": "^3.1.3",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-grid-layout": "^0.16.6",
    "react-scripts": "2.1.1",
    "react-testing-library": "^6.1.2"`

**Comment by kentcdodds** [comment]
Hi @LukenAgile42,

This is true whether you use react-testing-library or not. Even if you style it to have `pointerEvents: 'none'`, if you dispatch a click event on the element, it'll still call event handlers.

My recommendation: Don't fire a click event if you don't want the click handler called. If you want to verify that `pointerEvents: 'none'` is working properly, then I think you're wasting your time honestly. Trust that the browser does its job correctly and don't bother testing this.

Either way, there's nothing we're going to do in this library to change this behavior. You may be able to make this library do it though: https://github.com/Gpx/user-event

Good luck!

**Comment by weeklyTea** [comment]
I use a UI library and they added `pointerEvents: 'none'` to come elements in the last version. After library upgrading i run all tests which successfully passed. After that I got issue in release: user couldn't click on some elements. Actually this issue had been covered by my tests but was not discovered while test running. As i know react-testing-library takes in account `display: none` isn't it possible to check whether element has `pointerEvents: none` or not?

**Comment by robreinhard** [comment]
I agree with @weeklyTea , there should be consistency in whether react-testing-library takes CSS into account.

**Comment by MatanBobi** [comment]
Hi @robreinhard and @weeklyTea!
It will be better to look at `display: none` as an accessibility feature and not as a CSS feature, since we're relying on the accessibility tree, an element with `display: none` isn't rendered and therefor won't be shown to the user.

> User agents determine an element's hidden status based on whether it is rendered, and the rendering is usually controlled by CSS. For example, an element whose display property is set to none is not rendered.

So `display: none;` in this case has a very important aspect in accessibility.
I'm not too familiar and couldn't find a reference about how and if `pointer-events` affect the accessibility tree.

**Comment by adbutterfield** [comment]
This issue is closed and all, so probably moot to comment here (@kentcdodds)?
But in my case, I have tests to make sure the submit button for forms are disabled until all the required fields on the form are filled in and valid. Disabled submit button also has `pointer-events: none` when disabled. The tests click the button when the form is invalid, in order to make sure it does not take you to the next step. 

I guess the alternative is to check that the button has the disabled property somehow? But that would go against the idea behind react-testing-library. Feels like too much testing implementation details...
