### ISSUE TITLE
Supporting Older Versions of React?

### ISSUE THREAD

**Issue by dwighthouse** [kentcdodds/react-testing-library#64]
* `react-testing-library` version: 2.3.0
* `node` version: 8.1.1
* `npm` (or `yarn`) version: 5.1.0
* `react` version: 0.14.7
* `react-dom` version: 0.14.7

### Relevant code or config

```javascript
const reactTestingLibrary = require('react-testing-library');
```

### What you did:

Simply importing `react-testing-library` when React-DOM is less than version 0.15.5 when [react-addons-test-utils was deprecated in favor of using `react-dom/test-utils`](https://www.npmjs.com/package/react-addons-test-utils).

### What happened:

Error message:

```
Error: Cannot find module 'react-dom/test-utils'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    ...
```

### Problem description:

I'm currently writing front end tests for some legacy code that had no existing tests in order to provide some security and confidence that the code will remain working as I upgrade to newer versions of libraries and improved app design.

Obviously, upgrading my version of React is a non-starter, since I'm writing these tests in preparation for doing just that.

Enzyme has failed me in multiple ways, simply being unable or unwilling to test what I need to test, though it does support React 14.

### Suggested solution:

Adjust codebase to handle `test-utils` being retrieved from `react-addons-test-utils` and make any necessary adjustments to the available API under that condition. Or, provide an alternative plugin or import for `react-testing-library` that handles a specific older version.

At the very least, update the `package.json` file to warn against using versions of React prior to 0.15.5.

**Comment by kentcdodds** [comment]
Hi @dwighthouse! Thanks for the issue!

What I recommend is create a file that you can import into any of your test files as if it's a node module like [this one](https://github.com/kentcdodds/testing-workshop/blob/master/client/test/til-client-test-utils.js) (specifically what the file is, not its contents, you can import that file anywhere in the tests as if it's a node module which is possible because of [this config](https://github.com/kentcdodds/testing-workshop/blob/master/client/jest.config.js#L11)). With a utils file in place, you could create your own version of `react-testing-library` by basically copying the contents of [this file](https://github.com/kentcdodds/react-testing-library/blob/master/src/index.js) and changing the things you need.

I don't want to complicate this library by adding support for very old versions of React. I think this is a pretty simple workaround.

If you find it overly complicated, feel free to fork this project and publish `react-14-testing-library` or something. The changes should be pretty minimal. Most of the power behind this library is in `dom-testing-library` anyway :)

Thanks! And good luck!
